USE DEMODATABASE;

CREATE OR REPLACE TABLE TABLE1(
NAME1 VARCHAR(20)
);

INSERT INTO TABLE1
VALUES
('NIKHIL'),
('VAIBHAV'),
(''),
(NULL),
('2'),
('2'),
(NULL),
('TRISHUL');

SELECT * FROM TABLE1;

CREATE OR REPLACE TABLE TABLE2(
NAME2 VARCHAR(20)
);

INSERT INTO TABLE2
VALUES
('NIKHIL'),
('3'),
(''),
(NULL),
('2'),
('2'),
(NULL),
('2');

SELECT * FROM TABLE2;

SELECT COUNT(*) FROM TABLE2;

SELECT DISTINCT *
FROM TABLE1 AS T1
INNER JOIN TABLE2 T2
ON T1.NAME1 = T2.NAME2; -- space come in inner join if its varchar

SELECT DISTINCT *
FROM TABLE1 AS T1
LEFT OUTER JOIN TABLE2 T2
ON T1.NAME1 = T2.NAME2; -- null and blank both comes in varchar datatype

SELECT DISTINCT *
FROM TABLE1 AS T1
RIGHT OUTER JOIN TABLE2 T2
ON T1.NAME1 = T2.NAME2;

-- FULL OUTER JOIN

SELECT * FROM TABLE1
UNION
SELECT * FROM TABLE2;

SELECT DISTINCT *
FROM TABLE1 AS T1
FULL OUTER JOIN TABLE2 T2
ON T1.NAME1 = T2.NAME2;

SELECT  DISTINCT *
FROM TABLE1 AS T1
CROSS JOIN TABLE2 T2;

SELECT DISTINCT *
FROM TABLE1 AS T1
JOIN TABLE1 T2
ON T1.NAME1 = T2.NAME1;
