USE DATABASE DEMO_DATABASE;

CREATE OR REPLACE TABLE ND_SALES
(
CUSTOMER_ID VARCHAR(1),
ORDER_DATE DATE,
PRODUCT_ID INT NOT NULL
);

DESCRIBE TABLE ND_SALES;

INSERT INTO ND_SALES
VALUES
('A', '2023-01-01', '1'),
('A', '2023-01-04', '2'),
('A', '2023-01-07', '2'),
('B', '2023-01-09', '3'),
('B', '2023-01-11', '4'),
('B', '2023-01-12', '4'),
('C', '2023-01-14', '5'),
('C', '2023-01-17', '6'),
('C', '2023-01-18', '6'),
('D', '2023-01-19', '7'),
('D', '2023-01-21', '7'),
('D', '2023-01-22', '8'),
('E', '2023-01-23', '8'),
('F', '2023-01-24', '9'),
('G', '2023-01-25', '10');

SELECT * FROM ND_SALES WHERE ORDER_DATE BETWEEN '2023-01-01' AND '2023-01-22';

DESCRIBE TABLE ND_SALES;

-- IF YOU WANT TO CREATE A TABLE STRUCTURE LIKE PREVIOUSLY CREATE TABLE GO WITH LIKE COMMAND

CREATE OR REPLACE TABLE ND_SALES_COPY LIKE ND_SALES;

--IF YOU WANT TO CREATE A TABLE STRUCTURE LIKE PREVIOUSLY CREATE TABLE ALONG WITH DATA

CREATE OR REPLACE TABLE ND_SALES_COPY_DATA AS
SELECT * FROM ND_SALES;

SELECT * FROM ND_SALES_COPY_DATA;

--IF YOU WANT TO CREATE A TABLE STRUCTURE LIKE PREVIOUSLY CREATE TABLE ALONG WITH DATA BUT SPECIFIC COLUMN

CREATE OR REPLACE TABLE ND_SALES_COP_DATA AS
SELECT CUSTOMER_ID, ORDER_DATE FROM ND_SALES;

SELECT * FROM ND_SALES_COPY_DATA;

--IF YOU WANT TO CREATE A TABLE STRUCTURE LIKE PREVIOUSLY CREATE TABLE BUT NOT WITH DATA BUT SPECIFIC COLUMN

CREATE OR REPLACE TABLE ND_SALES_COPY LIKE ND_SALES ORDER BY ('CUSTOMER_ID', 'ORDER_DATE');--WRONG CODE

-- ALTER COMMAND IS USED TO ADD NEW DATA IN EXISTING TABLE

-- ADD A PRIMARY KEY TO AN EXISTING COLUMN

ALTER TABLE ND_SALES_COPY_DATA
ADD PRIMARY KEY (CUSTOMER_ID);

--DROP THE PK AND CREATE A NEW COLUMN TO THE EXISTING COLUMN AND MAKE IT PK

ALTER TABLE ND_SALES_COPY_DATA
DROP PRIMARY KEY;

-- ADD A COLUMN AND MAKE THAR PK

ALTER TABLE ND_SALES_COPY_DATA -- ONLY WORKS WHEN TABLE IS EMPTY
ADD COLUMN ADHAAR_NO VARCHAR(15) PRIMARY KEY;

-- ADD A COLUMN AND MAKE THAR PK WHEN TABLE IS NOT EMPTY

ALTER TABLE ND_SALES_COPY_DATA
ADD COLUMN ADHAAR_NO VARCHAR(15);

ALTER TABLE ND_SALES_COPY_DATA
ADD COLUMN AGE INT;

-- ADD THE COLUMN FIRST AND THEN MAKE IT PK USING 2 STEP COMMAND

ALTER TABLE ND_SALES_COPY_DATA
ADD PRIMARY KEY (ADHAAR_NO);

DESCRIBE TABLE ND_SALES_COPY_DATA;

-- DATA DEFINATION LAUNGUAGE TO SEE THA DATATYPE OF GIVEN DATA

SELECT GET_DDL('TABLE', 'ND_SALES_COPY_DATA');

-- WHEREEVER ADHAAR NO IS NULL I WANT THIS XXXX-XXXX-XXXX

UPDATE ND_SALES_COPY_DATA
SET ADHAAR_NO = 'XXXX-XXXX-XXXX' WHERE ADHAAR_NO IS NULL;